### ISSUE TITLE
WeTV無字幕/ WeTV Without subtitle

### ISSUE THREAD

**Issue by ChunlyShen** [jaysonlong/webvideo-downloader#128]
WeTV的字幕連結是錯的，所以下載合併後影片不會顯示字幕。請問有辦法修改嗎?謝謝。

**Comment by Sparh4wk** [comment]
its been already reported in #126

**Comment by peedan** [comment]
Please solve the problem. 
It happened for many days(two week or longer?).
Thank you, @jaysonlong

**Comment by ChunlyShen** [comment]
I open the "dispatcher.py" file and try to print the "subtitles" variable that **I find the download link is incorrect**, please see below
![image](https://user-images.githubusercontent.com/101887887/160141814-8d2e29bb-9dee-4909-825b-7c35cc26f430.png)
![image](https://user-images.githubusercontent.com/101887887/160141992-73b9d585-3f79-4908-9754-b7eb6cdea079.png)

For example, Subtitles URL is: 'https://subtitle.wetvinfo.com/svp_50125/cdv-ATVenqQXzlY2xukZ_Qc8Ns_J-DCZy28GXQT5gNJf0x5wLpg93mSNkBH0BueEOrxfDvhEX_UfS9lk2pMZATDKEF4Rn4niLUhNJnEse758eLTJtTc_ztfmx6AIsd2irswrLTEwc2IEw70dXrwdmA/gzc_1000117_0b53jaaccaaaqeal4o5vbzqm2sgdefcaajca.f490105.vtt.m3u8?ver=4' (incorrect)

We can see the URL last name is:"**.vtt.m3u8?ver=4**"
However, the correct URL last name should be: "**.vtt**"  

Therefore, **the correct URL is**: 'https://subtitle.wetvinfo.com/svp_50125/cdv-ATVenqQXzlY2xukZ_Qc8Ns_J-DCZy28GXQT5gNJf0x5wLpg93mSNkBH0BueEOrxfDvhEX_UfS9lk2pMZATDKEF4Rn4niLUhNJnEse758eLTJtTc_ztfmx6AIsd2irswrLTEwc2IEw70dXrwdmA/gzc_1000117_0b53jaaccaaaqeal4o5vbzqm2sgdefcaajca.f490105.vtt' (correct)

I only know the error, but I don't know how to fix it.

**Comment by maradonaz** [comment]
> I open the "dispatcher.py" file and try to print the "subtitles" variable that **I find the download link is incorrect**, please see below ![image](https://user-images.githubusercontent.com/101887887/160141814-8d2e29bb-9dee-4909-825b-7c35cc26f430.png) ![image](https://user-images.githubusercontent.com/101887887/160141992-73b9d585-3f79-4908-9754-b7eb6cdea079.png)
> 
> For example, Subtitles URL is: 'https://subtitle.wetvinfo.com/svp_50125/cdv-ATVenqQXzlY2xukZ_Qc8Ns_J-DCZy28GXQT5gNJf0x5wLpg93mSNkBH0BueEOrxfDvhEX_UfS9lk2pMZATDKEF4Rn4niLUhNJnEse758eLTJtTc_ztfmx6AIsd2irswrLTEwc2IEw70dXrwdmA/gzc_1000117_0b53jaaccaaaqeal4o5vbzqm2sgdefcaajca.f490105.vtt.m3u8?ver=4' (incorrect)
> 
> We can see the URL last name is:"**.vtt.m3u8?ver=4**" However, the correct URL last name should be: "**.vtt**"
> 
> Therefore, **the correct URL is**: 'https://subtitle.wetvinfo.com/svp_50125/cdv-ATVenqQXzlY2xukZ_Qc8Ns_J-DCZy28GXQT5gNJf0x5wLpg93mSNkBH0BueEOrxfDvhEX_UfS9lk2pMZATDKEF4Rn4niLUhNJnEse758eLTJtTc_ztfmx6AIsd2irswrLTEwc2IEw70dXrwdmA/gzc_1000117_0b53jaaccaaaqeal4o5vbzqm2sgdefcaajca.f490105.vtt' (correct)
> 
> I only know the error, but I don't know how to fix it.
> 
> By the way, if someone wants to download subtitles they can print "subtitles variable" to get the correct link before the error is fixed.

How do I get the subtitle link using command line I'm new to this.

**Comment by maradonaz** [comment]
> I open the "dispatcher.py" file and try to print the "subtitles" variable that **I find the download link is incorrect**, please see below ![image](https://user-images.githubusercontent.com/101887887/160141814-8d2e29bb-9dee-4909-825b-7c35cc26f430.png) ![image](https://user-images.githubusercontent.com/101887887/160141992-73b9d585-3f79-4908-9754-b7eb6cdea079.png)
> 
> For example, Subtitles URL is: 'https://subtitle.wetvinfo.com/svp_50125/cdv-ATVenqQXzlY2xukZ_Qc8Ns_J-DCZy28GXQT5gNJf0x5wLpg93mSNkBH0BueEOrxfDvhEX_UfS9lk2pMZATDKEF4Rn4niLUhNJnEse758eLTJtTc_ztfmx6AIsd2irswrLTEwc2IEw70dXrwdmA/gzc_1000117_0b53jaaccaaaqeal4o5vbzqm2sgdefcaajca.f490105.vtt.m3u8?ver=4' (incorrect)
> 
> We can see the URL last name is:"**.vtt.m3u8?ver=4**" However, the correct URL last name should be: "**.vtt**"
> 
> Therefore, **the correct URL is**: 'https://subtitle.wetvinfo.com/svp_50125/cdv-ATVenqQXzlY2xukZ_Qc8Ns_J-DCZy28GXQT5gNJf0x5wLpg93mSNkBH0BueEOrxfDvhEX_UfS9lk2pMZATDKEF4Rn4niLUhNJnEse758eLTJtTc_ztfmx6AIsd2irswrLTEwc2IEw70dXrwdmA/gzc_1000117_0b53jaaccaaaqeal4o5vbzqm2sgdefcaajca.f490105.vtt' (correct)
> 
> I only know the error, but I don't know how to fix it.
> 
> By the way, if someone wants to download subtitles they can print "subtitles variable" to get the correct link before the error is fixed.

Thank you this was of great help in getting the subtitles even if I have a separate file.

**Comment by enaskr** [comment]
When I opened .vtt file, I knew just added 8 lines on top of the file.
Remove just 8 lines and rename .srt, it worked fine.

**Comment by chathos** [comment]
> I open the "dispatcher.py" file and try to print the "subtitles" variable that **I find the download link is incorrect**, please see below ![image](https://user-images.githubusercontent.com/101887887/160141814-8d2e29bb-9dee-4909-825b-7c35cc26f430.png) ![image](https://user-images.githubusercontent.com/101887887/160141992-73b9d585-3f79-4908-9754-b7eb6cdea079.png)
> 
> For example, Subtitles URL is: 'https://subtitle.wetvinfo.com/svp_50125/cdv-ATVenqQXzlY2xukZ_Qc8Ns_J-DCZy28GXQT5gNJf0x5wLpg93mSNkBH0BueEOrxfDvhEX_UfS9lk2pMZATDKEF4Rn4niLUhNJnEse758eLTJtTc_ztfmx6AIsd2irswrLTEwc2IEw70dXrwdmA/gzc_1000117_0b53jaaccaaaqeal4o5vbzqm2sgdefcaajca.f490105.vtt.m3u8?ver=4' (incorrect)
> 
> We can see the URL last name is:"**.vtt.m3u8?ver=4**" However, the correct URL last name should be: "**.vtt**"
> 
> Therefore, **the correct URL is**: 'https://subtitle.wetvinfo.com/svp_50125/cdv-ATVenqQXzlY2xukZ_Qc8Ns_J-DCZy28GXQT5gNJf0x5wLpg93mSNkBH0BueEOrxfDvhEX_UfS9lk2pMZATDKEF4Rn4niLUhNJnEse758eLTJtTc_ztfmx6AIsd2irswrLTEwc2IEw70dXrwdmA/gzc_1000117_0b53jaaccaaaqeal4o5vbzqm2sgdefcaajca.f490105.vtt' (correct)
> 
> I only know the error, but I don't know how to fix it.
> 
> By the way, if someone wants to download subtitles they can print "subtitles variable" to get the correct link before the error is fixed.

Link has no problem but ffmpeg downloader not downloading vtt .

**Comment by enaskr** [comment]
I fixed this case for only WeTV. I learned python just 10 days. This is dispatcher.py.
![image](https://user-images.githubusercontent.com/62163013/162547576-6dc34ebf-7d3f-4ad3-805c-5a5a989dcd12.png)

**Comment by enaskr** [comment]
I fixed this issue. but my source is dirty. I learned python just 10 days. This is part of dispatcher.py.
I confirmed only WeTV and IQIYI.

`
    def handleStream(self, fileName, audioFormat, videoFormat, **desc):
        print("-- dispatcher/handleStream")

        audioName = tools.join(self.tempFilePath, fileName + '.audio' + audioFormat)
        videoName = tools.join(self.tempFilePath, fileName + '.video' + videoFormat)
        targetFileName = tools.join(self.videoFilePath, fileName + '.mp4.temp')

        self.downloader.saveStream(audioName, videoName, **desc)
        tools.mergeAudio2Video([audioName], [videoName], targetFileName)

        self.saveTempFile or tools.removeFiles([audioName, videoName])
        print('Finish %s\n' % targetFileName)
        return targetFileName

    def vtt_to_srt(self, vttFile):
        myFile = open(vttFile, 'r')
        vttfile = myFile.readlines()
        myFile.close()

        for i in range(0,15):
            if ( vttfile[i].startswith('1') ):
                break
            vttfile[i]=''

        srtFileName = vttFile.replace(".vtt",".srt")
        srtFile = open(srtFileName, 'a')
        srtFile.writelines(vttfile)
        srtFile.close()

    def handleSubtitles(self, subtitles, fileName, videoName, headers = {}):
        print("-- dispatcher/handleSubtitles")
        subtitleUrls, subtitleNames, subtitleNames1 = [], [], []
        subtitlesInfo, subtitlesInfo1 = [], []

        for name, url in subtitles:
            url = url.replace(".m3u8","")
            subtitleUrls.append(url)
            subtitleName = tools.join(self.tempFilePath, '%s_%s%s' % \
                (fileName, name, tools.getSuffix(url)))
            subtitleNames1.append(subtitleName)
            subtitlesInfo1.append((name, subtitleName))

        self.downloader.downloadAll(subtitleUrls, subtitleNames1, headers, self.hlsThreadCnt)

        for each in subtitleNames1:
            if ( ".vtt" in each ):
                self.vtt_to_srt(each)
                each = each.replace(".vtt",".srt")
                subtitleNames.append(each)
                tools.tryFixSrtFile(each)
                each = each.replace(".srt",".vtt")
                os.remove(each)
            else:
                subtitleNames.append(each)
                tools.tryFixSrtFile(each)

        for name1, each1 in subtitlesInfo1:
            if ( ".vtt" in each1 ):
                each1 = each1.replace(".vtt",".srt")
            subtitlesInfo.append((name1, each1))

        targetFileName = tools.integrateSubtitles(subtitlesInfo, videoName)
        self.saveTempFile or tools.removeFiles(subtitleNames)
        return targetFileName
`

**Comment by ssettor** [comment]
> > Hi @enaskr.
> > Sorry, I'm new that I change my code to your code and I get the error msg.
> > ![image](https://user-images.githubusercontent.com/101887887/162746379-76fff34e-56a4-4e8b-b20e-35d2b9725cae.png)
> 
> The below photo is my code. What's wrong with my code? ![image](https://user-images.githubusercontent.com/101887887/162747283-ab6f1559-446a-4701-8ce2-ffc1a85d32fd.png)
> 
> ![image](https://user-images.githubusercontent.com/101887887/162747514-1d2330f4-1aac-4d23-abdd-32a1519350e6.png)

line 97 myFile = open(vttFile, 'r', encoding='utf-8')
line 107 srtFile = open(srtFileName, 'a', encoding='utf-8')

**Comment by ChunlyShen** [comment]
> 

Hi @ssettor,
Thanks a lot for your reply! I edited the code and it can work now! Thank you so much!!! : )

In summary, just follow @enaskr 's code (https://github.com/jaysonlong/webvideo-downloader/issues/128#issuecomment-1093729341 ). However, if it get some unicode error, please edit below (https://github.com/jaysonlong/webvideo-downloader/issues/128#issuecomment-1099816625):
1. find 「myFile = open(vttFile, 'r')」 ,and change to => 「myFile = open(vttFile, 'r', encoding='utf-8')」
2. find 「srtFile = open(srtFileName, 'a')」, and change to => 「open(srtFileName, 'a', encoding='utf-8')」

**Comment by peedan** [comment]
> > 
> 
> Hi @ssettor, Thanks a lot for your reply! I edited the code and it can work now! Thank you so much!!! : )
> 
> In summary, just follow @enaskr 's code ([#128 (comment)](https://github.com/jaysonlong/webvideo-downloader/issues/128#issuecomment-1093729341) ). However, if it get some unicode error, please edit below ([#128 (comment)](https://github.com/jaysonlong/webvideo-downloader/issues/128#issuecomment-1099816625)):
> 
> 1. find 「myFile = open(vttFile, 'r')」 ,and change to => 「myFile = open(vttFile, 'r', encoding='utf-8')」
> 2. find 「srtFile = open(srtFileName, 'a')」, and change to => 「open(srtFileName, 'a', encoding='utf-8')」

Hi @ChunlyShen 

I have tried many times but it still cannot work.
Would you please upload your dispatcher.py to any public free space, such as mega, GD,....etc ?
Thanks a lot.

**Comment by ChunlyShen** [comment]
> 

@peedan 
Sure：
https://drive.google.com/file/d/1a5r5rMX_Ro3BLrUv1SX189OdHi-IbLMS/view?usp=sharing 
However, some videos can work, and some videos can't. I am still trying to find why.

**I guess the problem gets from [.srt merge to .mp4]**.

**Comment by ChunlyShen** [comment]
I found [.srt merge to .mp4] get error reason, it because of "the subtitles file format".

For example:

When I download to get the error, the .srt file are saved to the temp folder. 
![image](https://user-images.githubusercontent.com/101887887/166133172-2a4ea0b7-5b8a-4e9f-a634-c68e04d51008.png)

![image](https://user-images.githubusercontent.com/101887887/166133190-b7be3a93-afcf-4053-bf2f-710c15011f85.png)

I compare all [.srt] file content and found something different in the content.

Please see below the photo-A, the time format is **00:00.000**
![image](https://user-images.githubusercontent.com/101887887/166133200-a266256c-77f9-499f-b159-717a063e1b67.png)

Please see below the photo-B, the time format is **00:00:00.000** 
![image](https://user-images.githubusercontent.com/101887887/166133235-a8e29f25-0387-47b2-a5cb-e321d72e704c.png)

There are [.srt] files that can work for the online player, however, **the program "merger function(.srt merge to .mp4)" can't work for the time format of photo-A**.

Therefore, solutions are two ways:
1. Edit the merger code to support the "00:00.000" time format.
2. Ignore the "00:00.000" time format .srt file, only get "00:00:00.000" .srt file, it can merger to .mp4.

For number 2, my solution is: I only want to get the ["繁體" .srt file] and the format is 00:00:00.000, so I edit my code, please see below:
![image](https://user-images.githubusercontent.com/101887887/166133585-6a8d5af3-a4fc-49d0-ac6f-430a954f9cf6.png)

![image](https://user-images.githubusercontent.com/101887887/166133538-844b1db5-b20c-4264-bb1c-0fe8fb0d30f4.png)

Finally, I can download the video successfully.
